- name: Docker build and push
  hosts: local
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build and tag Docker image for Docker Hub
      command: docker build -t albertarko/web-apptwo:latest .
      args:
        chdir: /var/lib/jenkins/workspace/albert-pipeline

    - name: Log into Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_TOKEN') }}"

    - name: Push Docker image to Docker Hub
      command: docker push albertarko/web-apptwo:latest


    - name: Run container
      command: docker run -d --name web-app-2 -p 8081:8000 albertarko/web-apptwo:latest
