- name: docker build and push
  hosts: local
  become: yes
  
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build docker image locally
      command: docker build -t web-app-2:latest .
      args:
        chdir: /var/lib/jenkins/workspace/albert-pipeline

    - name: Tag image with Docker Hub username
      command: docker tag web-app-2:latest albertarko/web-app-2:latest

    - name: Log into Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Push image to Docker Hub
      command: docker push {{ lookup('env', 'DOCKER_USERNAME') }}/web-app-2:latest

    - name: Run container
      command: docker run -d --name web-app-2 -p 8081:8000 {{ lookup('env', 'DOCKER_USERNAME') }}/web-app-2:latest
