- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes
  
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build docker image
      command: docker build -t web-app-2 .
      args:
        chdir: /var/lib/jenkins/workspace/albert-pipeline

    - name: Tag image
      command: docker tag web-app-2:latest albertarko/web-app-2:latest

    - name: Log into Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"


    - name: Push image to Docker Hub
      command: docker push albertarko/web-app-2:latest

    - name: Run container
      command: docker run -d --name web-app-2 -p 8081:8000 albertarko/web-app-2:latest